### PR TITLE
Adding hot dog recipe

### PR DESCRIPTION
**Pull request by Sunguook**

### CODE REVIEW

**Comment by Sunguook** [comment]
Add your sauce.

**Comment by hjsohn** [comment]
Can you add mayo @hjsohn ?

**Comment by danisoul** [comment]
Add jalapeno and kimchi with bulgogi sauce too! @kimericd @hjsohn @Sunguook

**Comment by kimericd** [comment]
Could you add @wheat bread and

**Comment by kimericd** [comment]
Add Tabasco, too @danisoul @hjsohn @Sunguook

**Pull request merged**
